#!/bin/bash

# When the system restarts the folder seems to get deleted
sudo mkdir -p /var/run/celery
sudo chown ubuntu:ubuntu /var/run/celery

# Restart celery server
sudo systemctl daemon-reload
sudo systemctl restart celeryd

# Restart Apache server
sudo service apache2 restart
