# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0002_rentdatabase_moveinday'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='numBedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
