# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0003_rentdatabase_numbedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
    ]
