# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0004_rentdatabase_air_conditioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='bath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='dishWasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='numBathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='washDryer_InHome',
            field=models.BooleanField(default=False),
        ),
    ]
