# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0005_auto_20170506_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='lon',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
