# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0007_auto_20170525_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='fitness_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='handicap_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='parking_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='pool_hot_tub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='storage_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='washerDryer_inBuilding',
            field=models.BooleanField(default=False),
        ),
    ]
