# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0008_auto_20170531_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdatabase',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='numBathrooms',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='numBedrooms',
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='airConditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='maxBathrooms',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='minBathrooms',
            field=models.IntegerField(default=0),
        ),
    ]
