# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0011_auto_20170531_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentdatabase',
            old_name='moveInDay',
            new_name='move_in_day',
        ),
        migrations.RenameField(
            model_name='rentdatabase',
            old_name='air_conditioning',
            new_name='washer_dryer_in_building',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='dish_washer',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='maxBathrooms',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='minBathrooms',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='washDryer_InHome',
        ),
        migrations.RemoveField(
            model_name='rentdatabase',
            name='washerDryer_inBuilding',
        ),
    ]
