# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0012_auto_20170531_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='bath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='dish_washer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='num_bathrooms',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='num_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentdatabase',
            name='wash_dryer_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
