# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0013_auto_20170531_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentdatabase',
            name='num_bathrooms',
        ),
    ]
