# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0014_remove_rentdatabase_num_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdatabase',
            name='num_bathrooms',
            field=models.IntegerField(default=0),
        ),
    ]
