# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.IntegerField(default=-1)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='Recent Buy Survey', max_length=200)),
                ('maxPrice', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeType', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('town_house', 'Town House')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RentingSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.IntegerField(default=-1)),
                ('created', models.DateField(auto_now_add=True)),
                ('air_conditioning', models.IntegerField(default=0)),
                ('wash_dryer_in_home', models.IntegerField(default=0)),
                ('dish_washer', models.IntegerField(default=0)),
                ('bath', models.IntegerField(default=0)),
                ('max_bathrooms', models.IntegerField(default=7)),
                ('min_bathrooms', models.IntegerField(default=0)),
                ('parking_spot', models.IntegerField(default=0)),
                ('washer_dryer_in_building', models.IntegerField(default=0)),
                ('elevator', models.IntegerField(default=0)),
                ('handicap_access', models.IntegerField(default=0)),
                ('pool_hot_tub', models.IntegerField(default=0)),
                ('fitness_center', models.IntegerField(default=0)),
                ('storage_unit', models.IntegerField(default=0)),
                ('name', models.CharField(default='Recent Rent Survey', max_length=200)),
                ('max_price', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('price_weight', models.IntegerField(default=0)),
                ('max_commute', models.IntegerField(default=0)),
                ('min_commute', models.IntegerField(default=0)),
                ('commute_weight', models.IntegerField(default=0)),
                ('move_in_date_start', models.DateField(default=django.utils.timezone.now)),
                ('move_in_date_end', models.DateField(default=django.utils.timezone.now)),
                ('num_bedrooms', models.IntegerField(default=0)),
                ('home_type', models.ManyToManyField(to='survey.HomeType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyingDestinations',
            fields=[
                ('destinations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Destinations')),
            ],
            bases=('survey.destinations',),
        ),
        migrations.CreateModel(
            name='RentingDestinations',
            fields=[
                ('destinations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Destinations')),
            ],
            bases=('survey.destinations',),
        ),
    ]
