# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_auto_20161214_2152'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.IntegerField(default=-1)),
                ('streetAddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='initialsurvey',
            name='user',
        ),
        migrations.CreateModel(
            name='RentingSurveyModel',
            fields=[
                ('initialsurveymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.InitialSurveyModel')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('survey.initialsurveymodel',),
        ),
        migrations.DeleteModel(
            name='InitialSurvey',
        ),
        migrations.AddField(
            model_name='initialsurveymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.UserProfile'),
        ),
    ]
