# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20161219_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeType', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='amountMaxCommuteHigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='amountMaxCommuteLow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='homeType',
            field=models.ManyToManyField(to='survey.HomeType'),
        ),
    ]
