# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 01:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20161219_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentingsurveymodel',
            name='homeType',
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='homeType',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.DeleteModel(
            name='HomeType',
        ),
    ]
