# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20161219_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialsurveymodel',
            name='zip_code',
            field=models.IntegerField(max_length=200),
        ),
    ]
