# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20161219_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='homeType',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('town_house', 'Town House')], max_length=200),
        ),
    ]
