# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20161219_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeType', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('town_house', 'Town House')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentingsurveymodel',
            name='homeType',
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='home_type',
            field=models.ManyToManyField(to='survey.HomeType'),
        ),
    ]
