# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20161219_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialsurveymodel',
            old_name='user',
            new_name='userProf',
        ),
    ]
