# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20161222_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='name',
            field=models.CharField(default='recent_rent_survey', max_length=200),
        ),
    ]
