# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20161222_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingSurveyModel',
            fields=[
                ('initialsurveymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.InitialSurveyModel')),
                ('name', models.CharField(default='recent_buy_survey', max_length=200)),
            ],
            bases=('survey.initialsurveymodel',),
        ),
    ]
