# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_initialsurveymodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialsurveymodel',
            name='created',
        ),
    ]
