# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20161223_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.RentingSurveyModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='initialsurveymodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='initialsurveymodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='initialsurveymodel',
            name='streetAddress',
        ),
        migrations.RemoveField(
            model_name='initialsurveymodel',
            name='zip_code',
        ),
    ]
