# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20161223_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyaddresses',
            name='survey',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='amountMaxCommuteHigh',
            new_name='maxPrice',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='amountMaxCommuteLow',
            new_name='minPrice',
        ),
        migrations.AddField(
            model_name='initialsurveymodel',
            name='city',
            field=models.CharField(default='Arlington', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialsurveymodel',
            name='state',
            field=models.CharField(default='MA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialsurveymodel',
            name='streetAddress',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialsurveymodel',
            name='zip_code',
            field=models.CharField(default='024', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SurveyAddresses',
        ),
    ]
