# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20170103_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingsurveymodel',
            name='maxPrice',
            field=models.IntegerField(default=0),
        ),
    ]
