# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_buyingsurveymodel_maxprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='name',
            field=models.CharField(default='Recent Rent Survey', max_length=200),
        ),
    ]
