# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20170116_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='maxCommute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='minCommute',
            field=models.IntegerField(default=0),
        ),
    ]
