# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20170202_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='surveyWeight',
            field=models.IntegerField(default=1),
        ),
    ]
