# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20170214_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingsurveymodel',
            name='name',
            field=models.CharField(default='Recent Buy Survey', max_length=200),
        ),
    ]
