# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20170219_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='moveinDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
