# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20170219_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='test',
            field=models.CharField(default='', max_length=200),
        ),
    ]
