# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_rentingsurveymodel_moveindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='numBedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
