# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_rentingsurveymodel_numbedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='moveinDate',
            field=models.DateField(default=datetime.date(2017, 2, 25)),
        ),
    ]
