# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20170225_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='moveinDate',
            field=models.DateField(default=datetime.datetime(2017, 2, 26, 4, 25, 4, 249538, tzinfo=utc)),
        ),
    ]
