# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20170225_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='airConditioning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='bath',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='dishWasher',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='maxBathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='minBathRooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='washDryer_InHome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='moveinDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
