# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20170314_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='minBathRooms',
            new_name='minBathrooms',
        ),
        migrations.AlterField(
            model_name='rentingsurveymodel',
            name='maxBathrooms',
            field=models.IntegerField(default=7),
        ),
    ]
