# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20170315_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='elevator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='fitnessCenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='handicapAccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='parkingSpot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='poolHottub',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='storageUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='washerDryer_inBuilding',
            field=models.IntegerField(default=0),
        ),
    ]
