# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20170315_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='moveinDate',
            new_name='move_in_date_end',
        ),
        migrations.AddField(
            model_name='rentingsurveymodel',
            name='move_in_date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
