# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_auto_20170328_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='move_in_date_end',
            new_name='moveinDateEnd',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='move_in_date_start',
            new_name='moveinDateStart',
        ),
    ]
