# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_rentingsurveymodel_test'),
        ('survey', '0037_auto_20170328_0022'),
    ]

    operations = [
    ]
