# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_rentingsurveymodel_price_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='fitnessCenter',
            new_name='fitness_center',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='handicapAccess',
            new_name='handicap_access',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='parkingSpot',
            new_name='parking_spot',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='poolHottub',
            new_name='pool_hot_tub',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='storageUnit',
            new_name='storage_unit',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='washerDryer_inBuilding',
            new_name='washer_dryer_in_building',
        ),
    ]
