# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_auto_20170601_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='commuteWeight',
            new_name='commute_weight',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='maxCommute',
            new_name='max_commute',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='maxPrice',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='minCommute',
            new_name='min_commute',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='minPrice',
            new_name='min_price',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='moveinDateEnd',
            new_name='move_in_date_end',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='moveinDateStart',
            new_name='move_in_date_start',
        ),
        migrations.RenameField(
            model_name='rentingsurveymodel',
            old_name='numBedrooms',
            new_name='num_bedrooms',
        ),
    ]
