# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_auto_20161210_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(default='Please enter somethign test', max_length=200),
            preserve_default=False,
        ),
    ]
