# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_userprofile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
