# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_remove_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
