# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0001_initial'),
        ('userAuth', '0009_remove_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(to='houseDatabase.RentDatabase'),
        ),
    ]
