# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseDatabase', '0005_auto_20170506_0846'),
        ('userAuth', '0010_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visit_list',
            field=models.ManyToManyField(related_name='vist_list', to='houseDatabase.RentDatabase'),
        ),
    ]
