# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_auto_20170513_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_list', to='houseDatabase.RentDatabase'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visit_list',
            field=models.ManyToManyField(blank=True, related_name='visit_list', to='houseDatabase.RentDatabase'),
        ),
    ]
